services:
  clews:
    build:
      context: .
      dockerfile: models/clews.Dockerfile
    container_name: clews-model
    working_dir: /app
    volumes:
      - ./models/clews:/app
    tty: true
    stdin_open: true

  discogs-vinet:
    platform: linux/amd64
    build:
      context: .
      dockerfile: models/discogs-vinet.Dockerfile
    container_name: discogs-vinet-model
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    working_dir: /app
    volumes:
      - ./models/Discogs-VINet:/app
    tty: true
    stdin_open: true
